      - name: Restore Session Cache
        uses: actions/cache@v3
        with:
          path: kabam_session.json
          key: ${{ runner.os }}-kabam-session

      - name: Run script
        env:
          KABAM_EMAIL: ${{ secrets.KABAM_EMAIL }}
          KABAM_PASSWORD: ${{ secrets.KABAM_PASSWORD }}
        run: python Collect_Rewards.py
