name: Collect Game Rewards

on:
  schedule:
    - cron: '0 13 35 * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium --with-deps

      - name: Run script
        env:
          KABAM_EMAIL: ${{ secrets.KABAM_EMAIL }}
          KABAM_PASSWORD: ${{ secrets.KABAM_PASSWORD }}
        run: python Collect_Rewards.py

      - name: Upload Screenshots (if failed)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: "*.png"
          retention-days: 7
